#!/bin/bash
source ./tools
source ./config

if ! [ $(id -u) = 0 ]
then
	echo "Please run as root."
	exit 1
fi

if [[ $# -ne 2 ]]
then
	echo "Usage: $0 originalfile.iso customfile.iso"
	exit 1
fi

if ! direxists edit || ! direxists mnt || ! direxists extract-cd
then
	exit 1
fi

# Rebuild list of packages
chmod +w extract-cd/$PACKAGE_MANIFEST
chroot edit dpkg-query -W --showformat='${Package} ${Version}\n' > extract-cd/$PACKAGE_MANIFEST

# Compress filesystem
rm -rf extract-cd/$SQUASHFS_DIR
mksquashfs edit extract-cd/$SQUASHFS_DIR

# Update filesystem size
printf $(du -sx --block-size=1 edit | cut -f1) > extract-cd/$SIZE_MANIFEST

# Rebuilt md5sum
cd extract-cd
rm ${CHECKSUM_FILE#/}
find -type f -print0 | xargs -0 $CHECKSUM_COMMAND | grep -v ${CHECKSUM_IGNORE_DIR#/} | tee ${CHECKSUM_FILE#/}
cd ..

## TODO ADD COMENTS

# Add initial options first
cat <<EOF >xorriso.conf
-as mkisofs \\
-r -J --joliet-long \\
-iso-level ${ISO_LEVEL} \\
-o $2 \\
EOF
# Use xorriso do the magic of figuring out options used to create original iso, making sure
# to append backslash to each line as required.
xorriso -report_about warning -indev "$1" -report_system_area as_mkisofs |
    sed -e 's|$| \\|'>>xorriso.conf
# Tell xorriso the root directory for the iso being created
echo 'extract-cd' >>xorriso.conf

# Modify options in xorriso.conf as desired or use as-is
xorriso -options_from_file xorriso.conf
