#!/bin/bash

source ./tools
source ./config

if [[ $# -eq 0 ]]
then
	echo "Usage: $0 file.iso"
	exit 1
fi

./preview $1

mkdir extract-cd 
sudo rsync --exclude=$SQUASHFS_DIR -a mnt/ extract-cd/

sudo unsquashfs mnt/$SQUASHFS_DIR
sudo mv squashfs-root edit













