#!/bin/bash

source ./tools

if [[ $# -eq 0 ]]
then
	echo "Usage: $0 file.iso"
	exit 1
fi

if [[ -d mnt ]] 
then
	sudo umount mnt
	rm -rf mnt
fi

mkdir mnt

sudo mount -o loop "$1" mnt/

removedir extract-cd
removedir edit

mkdir extract-cd 
sudo rsync --exclude=/casper/filesystem.squashfs -a mnt/ extract-cd/

sudo unsquashfs mnt/casper/filesystem.squashfs
sudo mv squashfs-root edit













